#pragma config(Sensor, S3,     Touch1,         sensorTouch)
#pragma config(Sensor, S4,     Touch2,         sensorTouch)
#pragma config(Motor,  motorA,          mA,            tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          mB,            tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          mC,            tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define CLOSED (20)
#define OPENED (-100)

int hold = CLOSED;
int position = 0;

task holder()
{
	nMotorEncoder[mA] = 0;
	while(true)
	{
		motor[mA] = 4*(hold - nMotorEncoder[mA]);
		wait1Msec(1);
	}
}

task screen()
{
	while(true)
	{
		nxtDisplayCenteredBigTextLine(3, "%d", position);
		wait1Msec(30);
	}
}

task main()
{
	StartTask(screen);
	StartTask(holder);
	hold = CLOSED;

	while((SensorValue[Touch1] == 0) || (SensorValue[Touch2] == 0)) wait1Msec(1);

	//start input
	position = 1;
	PlaySound(soundBeepBeep);

	while((SensorValue[Touch1] == 1) || (SensorValue[Touch2] == 1)) wait1Msec(1);
	wait1Msec(5000);
	while((SensorValue[Touch1] == 0) || (SensorValue[Touch2] == 0)) wait1Msec(1);
	wait1Msec(5000);

  position = 2;
  PlaySound(soundBeepBeep);

	nMotorEncoder[motorC] = 0;
	nMotorEncoder[motorB] = 0;
	motor[mB] = 10;
	motor[mC] = 10;
	while((nMotorEncoder[motorB] < 500) || (nMotorEncoder[motorB] < 500)) wait1Msec(1);
	while((SensorValue[Touch1] == 0) || (SensorValue[Touch2] == 0)) wait1Msec(1);
	motor[mB] = 0;
	motor[mC] = 0;

	position = 3;//vburivanie
  PlaySound(soundBeepBeep);

  wait1Msec(9000);

  position = 4;//opening
  PlaySound(soundBeepBeep);

  hold = OPENED;
	wait1Msec(3000);

  position = 5;//otezd posle vburivania
  PlaySound(soundBeepBeep);

  wait1Msec(20000);

  position = 6;//ubiranie shvata
  PlaySound(soundBeepBeep);

  nMotorEncoder[motorC] = 0;
	nMotorEncoder[motorB] = 0;
	motor[mB] = -20;
	motor[mC] = -20;
	while((nMotorEncoder[motorB] > -500) || (nMotorEncoder[motorB] > -500)) wait1Msec(1);
	motor[mB] = 0;
	motor[mC] = 0;
}
