#pragma config(Sensor, S3,     Touch1,         sensorTouch)
#pragma config(Sensor, S4,     Touch2,         sensorTouch)
#pragma config(Motor,  motorA,          mA,            tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          mB,            tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          mC,            tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int position = 0;

#include "2tasks.h"

task main()
{
	StartTask(screen);
	StartTask(holder);

	//PD-reg
	position = 1;
	while(isAnyTouched() == false) wait1Msec(1);

	//Aligning
	position = 2;
	while(isAllTouched() == false) wait1Msec(1);

	//Reverse driving
	position = 3;
	wait1Msec(1000);

	//Special-reg
	position = 4;
	while(isAnyTouched() == false) wait1Msec(1);

	//Aligning. Again.
	position = 5;
	while(isAllTouched() == false) wait1Msec(1);

	//Small reverse driving
	position = 6;
	wait1Msec(2000);

	//Setting Research Module
	position = 7;
	setModule();

	//Drilling
	PlaySound(soundDownwardTones);
	position = 8;
	wait1Msec(12000);
	hold = OPENED;
	wait1Msec(1000);

	//Reverse driving
	PlaySound(soundDownwardTones);
	position = 9;
	wait1Msec(5000);

	//Set platform back
	hold = CLOSED;
	position = 10;
	setPlatform();

	//DEMO
	wait1Msec(100000);//------------------------------- LONG WAITING -----------------------------------------------
	PlaySound(soundUpwardTones);
	PlaySound(soundDownwardTones);
	wait1Msec(20000);
	position = 10;
	wait1Msec(10000);
	position = 11;
	wait1Msec(5000);
	position = 12;
	for(int x = 1; x <= 1; x++)
	{
		nMotorEncoder[motorC] = 0;
		nMotorEncoder[motorB] = 0;
		motor[mB] = 30;
		motor[mC] = 30;
		while(nMotorEncoder[motorB] < 500) wait1Msec(1);
		motor[mB] = 0;
		motor[mC] = 0;
		wait1Msec(500);
		hold = OPENED;
		wait1Msec(1000);
		motor[mB] = -30;
		motor[mC] = -30;
		while(nMotorEncoder[motorB] > 0){
			if (nMotorEncoder[motorB] < 150) hold = CLOSED;
			wait1Msec(1);
		}
		motor[mB] = 0;
		motor[mC] = 0;
		wait1Msec(500);
	}
}
