#pragma config(Sensor, S1,     Touch1,         sensorTouch)
#pragma config(Sensor, S2,     Touch2,         sensorTouch)
#pragma config(Motor,  motorA,          cam,           tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          mB,            tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          mC,            tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int position = 0;
int inputMessage = 0;

void StopAndWait(int n)
{
	motor[motorB] = 0;
	motor[motorC] = 0;
	wait1Msec(n);
}

void Motors(int mmB, int mmC)
{
	motor[motorB] = mmB;
	motor[motorC] = mmC;
}

void ZeroEnc()
{
	nMotorEncoder[motorB] = 0;
	nMotorEncoder[motorC] = 0;
}

task screen()
{
	while(true)
	{
		nxtDisplayCenteredBigTextLine(2, "%d", position);
		wait1Msec(30);
	}
}

task sendPosition()
{
	while(true)
	{
		sendMessageWithParm(position, 0, 0);
		wait1Msec(30);
	}
}

void waitForMessage(int pos)
{
	inputMessage = 0;
	while(inputMessage != pos)
	{
		if(cCmdMessageGetSize(mailbox1) != 0)
		{
			inputMessage = messageParm[0];
			ClearMessage();
		}
		wait1Msec(30);
	}
}

task main()
{
	StartTask(sendPosition);
	StartTask(screen);

	position = 0;
	PlaySound(soundBeepBeep);
	ZeroEnc();
	Motors(20, 20);
	while(abs(nMotorEncoder[mB]) < 500) wait1Msec(1);
	Motors(0, 0);
	ZeroEnc();
	Motors(-40, -10);
	while(abs(nMotorEncoder[mB]) < 1700) wait1Msec(1);
	Motors(0, 0);
	ZeroEnc();
	Motors(20, 20);
	while(abs(nMotorEncoder[mB]) < 400) wait1Msec(1);
	Motors(0, 0);

	position = 1;
	PlaySound(soundBeepBeep);
	wait1Msec(3000);
	for(int x = 1; x <= 3; x++)
	{
		nMotorEncoder[motorA] = 0;
		motor[motorA] = 10;
		while(nMotorEncoder[motorA] < 90) wait1Msec(1);
		wait1Msec(500);
		motor[motorA] = - 10;
		while(nMotorEncoder[motorA] > 0) wait1Msec(1);
	}
	motor[motorA] = 0;

	position = 2;
	PlaySound(soundBeepBeep);
	waitForMessage(3);

	position = 3;
	PlaySound(soundBeepBeep);
}
