#pragma config(Sensor, S3,     Touch1,         sensorTouch)
#pragma config(Sensor, S4,     Touch2,         sensorTouch)
#pragma config(Motor,  motorA,          mA,            tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          mB,            tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          mC,            tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int position = 0;
int inputMessage = 0;

#define CLOSED (20)
#define OPENED (-100)

int hold = CLOSED;

task holder()
{
	nMotorEncoder[mA] = 0;
	while(true)
	{
		motor[mA] = 6*(hold - nMotorEncoder[mA]);
		wait1Msec(1);
	}
}

task screen()
{
	while(true)
	{
		nxtDisplayCenteredBigTextLine(2, "%d", position);
		wait1Msec(30);
	}
}

task sendPosition()
{
	while(true)
	{
		sendMessageWithParm(position, 0, 0);
		wait1Msec(30);
	}
}

void waitForMessage(int pos)
{
	inputMessage = 0;
	while(inputMessage != pos)
	{
		if(cCmdMessageGetSize(mailbox1) != 0)
		{
			inputMessage = messageParm[0];
			ClearMessage();
		}
		wait1Msec(30);
	}
}

task main()
{
	StartTask(sendPosition);
	StartTask(screen);
	StartTask(holder);

	position = 0;
	PlaySound(soundBeepBeep);
	waitForMessage(1);

	position = 1;
	PlaySound(soundBeepBeep);
	wait1Msec(3000);
	waitForMessage(2);

	position = 2;
	wait1Msec(3000);
	for(int x = 1; x <= 1; x++)
	{
		nMotorEncoder[motorC] = 0;
		nMotorEncoder[motorB] = 0;
		motor[mB] = 30;
		motor[mC] = 30;
		while(nMotorEncoder[motorB] < 500) wait1Msec(1);
		motor[mB] = 0;
		motor[mC] = 0;
		wait1Msec(500);
		hold = OPENED;
		wait1Msec(1000);
		motor[mB] = -30;
		motor[mC] = -30;
		while(nMotorEncoder[motorB] > 0){
			if (nMotorEncoder[motorB] < 150) hold = CLOSED;
			wait1Msec(1);
		}
		motor[mB] = 0;
		motor[mC] = 0;
		wait1Msec(500);
	}

	position = 3;
	PlaySound(soundBeepBeep);
}
